@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node0 as "POSTGRES - users  /* Зарегистрированные пользователи */" {
   id  /* ID */: bigint
   username  /* логин */: varchar
   email  /* почта */: varchar
   password  /* пароль */: varchar
   role  /* роль */: varchar
   activation_key  /* ключ активации */: varchar
   is_active  /* активирован? */: varchar
   created_at  /* время создания */: datetime
   updated_at  /* время обновления */: datetime
   created_by  /* логин */: varchar
   updated_by  /* логин */: varchar
}

class node1 as "POSTGRES - companies  /* Компании */" {
   id  /* ID */: smallint
   ticker  /* тикер */: varchar
}

class node2 as "REDIS - stocks  /* Стоки компаний */" {
   ticker  /* тикер */: varchar
   stock  /* цена */: bigint
   actual_on  /* актуальное время */: datetime
}

@enduml
